apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: add
      path: /spec/source/path
      value: apps/envs/prod
  target:
    name: apps
- patch: |-
    - op: add
      path: /spec/source/path
      value: argo-cd/envs/prod
  target:
    name: argo-cd
- patch: |-
    - op: add
      path: /spec/source/path
      value: ops/envs/prod
  target:
    name: ops
